# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('professor', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('has_pale', models.NullBooleanField()),
                ('has_project', models.NullBooleanField()),
                ('has_presentation', models.NullBooleanField()),
                ('has_oral', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigram', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Department'),
        ),
        migrations.AddField(
            model_name='class',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Period'),
        ),
        migrations.AddField(
            model_name='class',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Type'),
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Year'),
        ),
    ]
