# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20170413_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'évalutation'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'cours'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'département'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'période'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'élève'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'type'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'année'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='assessment',
            name='comment',
            field=models.TextField(default='', verbose_name='commentaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=6, verbose_name='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rate.Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='amphi_grade',
            field=models.IntegerField(verbose_name="note d'amphi"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Course', verbose_name='cours'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='difficulty_grade',
            field=models.IntegerField(verbose_name='note de difficulté'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='interest_grade',
            field=models.IntegerField(verbose_name="note d'intérêt"),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pc_grade',
            field=models.IntegerField(verbose_name='note de PC'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rate.Student', verbose_name='élève'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_oral',
            field=models.NullBooleanField(verbose_name='oral'),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_pale',
            field=models.NullBooleanField(verbose_name='pâle'),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_presentation',
            field=models.NullBooleanField(verbose_name='présentation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_project',
            field=models.NullBooleanField(verbose_name='projet'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(max_length=254, verbose_name='professeur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=254, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=254, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='department',
            name='trigram',
            field=models.CharField(max_length=254, verbose_name='trigramme'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=254, verbose_name='période'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=254, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promotion',
            field=models.CharField(max_length=12, verbose_name='promotion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=254, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=254, verbose_name='année'),
        ),
    ]
