# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20170413_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rate.Department', verbose_name='département'),
            preserve_default=False,
        ),
    ]
