# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_assessment_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'cours', 'verbose_name_plural': 'cours'},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='department',
        ),
    ]
